spring.application.name=breeder_revamp
server.port=8091

#spring.datasource.url=jdbc:oracle:thin:@10.4.1.43:1601/TESTPRE
#spring.datasource.url=jdbc:oracle:thin:@10.4.1.25:1541/PROD
#spring.datasource.url=jdbc:oracle:thin:@10.4.1.62:1552/PREPROD
spring.datasource.url=jdbc:oracle:thin:@10.4.1.49:1530/TEST
spring.datasource.username=apps
spring.datasource.password=sugapps

# Properties for UCP - Universal Connection Pool (UCP). Spring Boot 2.4.0 or above is required
#spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
# Enable JPA / Hibernate debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

#hibernate configs
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

#logging.level.org.springframework.web.client.RestTemplate=DEBUG

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080

